# Generated by Django 3.1.5 on 2021-04-09 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('craft_type', models.CharField(max_length=45)),
                ('created_date', models.DateField()),
                ('num', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_craft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crafter', to='CrafterMall.users')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('street_Add', models.CharField(max_length=75)),
                ('unit_num', models.CharField(default='N/A', max_length=10)),
                ('state', models.CharField(max_length=15)),
                ('zip_code', models.IntegerField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='CrafterMall.users')),
            ],
        ),
    ]
