# Generated by Django 3.1.5 on 2021-04-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrafterMall', '0002_auto_20210408_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='CodingTonVille', max_length=30),
        ),
    ]
