# Generated by Django 3.1.5 on 2021-04-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrafterMall', '0003_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='has_store',
            field=models.BooleanField(default=False),
        ),
    ]
