# Generated by Django 3.1.5 on 2021-04-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrafterMall', '0004_users_has_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='store_name',
            field=models.CharField(default='None', max_length=45),
        ),
    ]
