# Generated by Django 3.1.5 on 2021-04-11 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CrafterMall', '0005_users_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='store_name',
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopkeep', to='CrafterMall.users')),
            ],
        ),
    ]
