# Generated by Django 3.2 on 2021-04-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrafterMall', '0007_auto_20210412_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='store_name',
            field=models.CharField(default='None', max_length=45),
        ),
    ]
