# Generated by Django 3.2 on 2021-04-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrafterMall', '0008_users_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='craft_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
