# Generated by Django 3.2 on 2021-04-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrafterMall', '0009_craft_craft_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craft',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='craft',
            name='num',
        ),
        migrations.AddField(
            model_name='craft',
            name='in_stock_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='craft',
            name='on_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='craft',
            name='craft_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images'),
        ),
        migrations.CreateModel(
            name='Keytags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craft_word', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.ManyToManyField(related_name='tag', to='CrafterMall.Craft')),
            ],
        ),
    ]
