# Generated by Django 3.2 on 2021-04-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrafterMall', '0011_auto_20210413_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craft',
            name='tags',
        ),
    ]
