# Generated by Django 3.2 on 2021-04-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrafterMall', '0013_alter_craft_craft_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craft',
            name='craft_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
