# Generated by Django 3.2 on 2021-04-15 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrafterMall', '0014_alter_craft_craft_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='craft',
            old_name='item_title',
            new_name='craft_name',
        ),
    ]
