# Generated by Django 3.2 on 2021-04-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrafterMall', '0016_digital_craft_jewelry_craft_leather_craft_metal_craft_textile_craft_wood_craft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Craft',
        ),
    ]
